// Code generated by gophermc/generator. DO NOT EDIT.
// See generator/main.go for more details.
package protocol

import "fmt"

type Version int

const (
	V1_7    Version = iota
	V1_8    Version = iota
	V1_9    Version = iota
	V1_9_2  Version = iota
	V1_9_4  Version = iota
	V1_10   Version = iota
	V1_11   Version = iota
	V1_12   Version = iota
	V1_12_1 Version = iota
	V1_12_2 Version = iota
	V1_13   Version = iota
	V1_13_1 Version = iota
	V1_13_2 Version = iota
	V1_14   Version = iota
	V1_14_1 Version = iota
	V1_14_3 Version = iota
	V1_14_4 Version = iota
	V1_15   Version = iota
	V1_15_1 Version = iota
	V1_15_2 Version = iota
	V1_16   Version = iota
	V1_16_1 Version = iota
	V1_16_2 Version = iota
	V1_17   Version = iota
	V1_17_1 Version = iota
	V1_18   Version = iota
	V1_18_2 Version = iota
	V1_19   Version = iota
	V1_19_2 Version = iota
	V1_19_3 Version = iota
	V1_19_4 Version = iota
	V1_20   Version = iota
	V1_20_2 Version = iota
	V1_20_3 Version = iota
	V1_20_5 Version = iota
	V1_21_1 Version = iota
	V1_21_3 Version = iota
	V1_21_4 Version = iota
	V1_21_5 Version = iota
	V1_21_6 Version = iota
	V1_21_8 Version = iota
)

const First = V1_7
const Latest = V1_21_8

var (
	stringToVersion map[string]Version
	versionToString map[Version]string
	Versions        []Version
)

func init() {
	stringToVersion = map[string]Version{
		"1.7":    V1_7,
		"1.8":    V1_8,
		"1.9":    V1_9,
		"1.9.2":  V1_9_2,
		"1.9.4":  V1_9_4,
		"1.10":   V1_10,
		"1.11":   V1_11,
		"1.12":   V1_12,
		"1.12.1": V1_12_1,
		"1.12.2": V1_12_2,
		"1.13":   V1_13,
		"1.13.1": V1_13_1,
		"1.13.2": V1_13_2,
		"1.14":   V1_14,
		"1.14.1": V1_14_1,
		"1.14.3": V1_14_3,
		"1.14.4": V1_14_4,
		"1.15":   V1_15,
		"1.15.1": V1_15_1,
		"1.15.2": V1_15_2,
		"1.16":   V1_16,
		"1.16.1": V1_16_1,
		"1.16.2": V1_16_2,
		"1.17":   V1_17,
		"1.17.1": V1_17_1,
		"1.18":   V1_18,
		"1.18.2": V1_18_2,
		"1.19":   V1_19,
		"1.19.2": V1_19_2,
		"1.19.3": V1_19_3,
		"1.19.4": V1_19_4,
		"1.20":   V1_20,
		"1.20.2": V1_20_2,
		"1.20.3": V1_20_3,
		"1.20.5": V1_20_5,
		"1.21.1": V1_21_1,
		"1.21.3": V1_21_3,
		"1.21.4": V1_21_4,
		"1.21.5": V1_21_5,
		"1.21.6": V1_21_6,
		"1.21.8": V1_21_8,
	}

	versionToString = make(map[Version]string)
	for s, v := range stringToVersion {
		versionToString[v] = s
		Versions = append(Versions, v)
	}
}

func (v Version) Protocol() int32 {
	if def := GetDefinition(v); def != nil {
		return def.ProtocolVersion
	}
	panic(fmt.Sprintf("protocol number missing for version %s", v))
}

func (v Version) String() string {
	if s, ok := versionToString[v]; ok {
		return s
	}
	return "Unknown"
}
